### ISSUE TITLE
Flexview•How long is the port down/up isn't working right

### ISSUE THREAD

**Issue by JohanHendrikx** [extremenetworks/Netsight-Report-Views#1]
The information of how long a port is up of down isn't correct while sysuptime is lower

![port-status](https://cloud.githubusercontent.com/assets/26381326/23856587/73b35d90-07fa-11e7-89b2-62d576984cb7.JPG)

**Comment by ZdenekPala** [comment]
hmm. what device is it?
just tested on XOS 15.3.5.2, XOS 22.1.1.5, EOS 5.2.19.0008, Cisco 12.2.53

Z.

**Comment by JohanHendrikx** [comment]
I did the test on XOS 15.3.5.2-patch1-9

**Comment by JohanHendrikx** [comment]
Strange.... I did an upgrade op Netsight and the problem is solved.

**Comment by ZdenekPala** [comment]
good. thx for feedback. what was the original version?

**Comment by JohanHendrikx** [comment]
Orginial version was 7.0.9.4
